# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/wik/clion-2016.3.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/wik/clion-2016.3.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/wik/Pulpit/Dokumenty Wiktora/V rok/Cranfield/High Performance Technical Computing"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/wik/Pulpit/Dokumenty Wiktora/V rok/Cranfield/High Performance Technical Computing"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/wik/clion-2016.3.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/wik/clion-2016.3.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/wik/Pulpit/Dokumenty Wiktora/V rok/Cranfield/High Performance Technical Computing/CMakeFiles" "/home/wik/Pulpit/Dokumenty Wiktora/V rok/Cranfield/High Performance Technical Computing/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/wik/Pulpit/Dokumenty Wiktora/V rok/Cranfield/High Performance Technical Computing/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named High_Performance_Technical_Computing

# Build rule for target.
High_Performance_Technical_Computing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 High_Performance_Technical_Computing
.PHONY : High_Performance_Technical_Computing

# fast build rule for target.
High_Performance_Technical_Computing/fast:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/build
.PHONY : High_Performance_Technical_Computing/fast

CrankParallel.o: CrankParallel.cpp.o

.PHONY : CrankParallel.o

# target to build an object file
CrankParallel.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/CrankParallel.cpp.o
.PHONY : CrankParallel.cpp.o

CrankParallel.i: CrankParallel.cpp.i

.PHONY : CrankParallel.i

# target to preprocess a source file
CrankParallel.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/CrankParallel.cpp.i
.PHONY : CrankParallel.cpp.i

CrankParallel.s: CrankParallel.cpp.s

.PHONY : CrankParallel.s

# target to generate assembly for a file
CrankParallel.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/CrankParallel.cpp.s
.PHONY : CrankParallel.cpp.s

Display.o: Display.cpp.o

.PHONY : Display.o

# target to build an object file
Display.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/Display.cpp.o
.PHONY : Display.cpp.o

Display.i: Display.cpp.i

.PHONY : Display.i

# target to preprocess a source file
Display.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/Display.cpp.i
.PHONY : Display.cpp.i

Display.s: Display.cpp.s

.PHONY : Display.s

# target to generate assembly for a file
Display.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/Display.cpp.s
.PHONY : Display.cpp.s

ExplicitUpwindParallel.o: ExplicitUpwindParallel.cpp.o

.PHONY : ExplicitUpwindParallel.o

# target to build an object file
ExplicitUpwindParallel.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ExplicitUpwindParallel.cpp.o
.PHONY : ExplicitUpwindParallel.cpp.o

ExplicitUpwindParallel.i: ExplicitUpwindParallel.cpp.i

.PHONY : ExplicitUpwindParallel.i

# target to preprocess a source file
ExplicitUpwindParallel.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ExplicitUpwindParallel.cpp.i
.PHONY : ExplicitUpwindParallel.cpp.i

ExplicitUpwindParallel.s: ExplicitUpwindParallel.cpp.s

.PHONY : ExplicitUpwindParallel.s

# target to generate assembly for a file
ExplicitUpwindParallel.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ExplicitUpwindParallel.cpp.s
.PHONY : ExplicitUpwindParallel.cpp.s

ExplicitUpwindScheme.o: ExplicitUpwindScheme.cpp.o

.PHONY : ExplicitUpwindScheme.o

# target to build an object file
ExplicitUpwindScheme.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ExplicitUpwindScheme.cpp.o
.PHONY : ExplicitUpwindScheme.cpp.o

ExplicitUpwindScheme.i: ExplicitUpwindScheme.cpp.i

.PHONY : ExplicitUpwindScheme.i

# target to preprocess a source file
ExplicitUpwindScheme.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ExplicitUpwindScheme.cpp.i
.PHONY : ExplicitUpwindScheme.cpp.i

ExplicitUpwindScheme.s: ExplicitUpwindScheme.cpp.s

.PHONY : ExplicitUpwindScheme.s

# target to generate assembly for a file
ExplicitUpwindScheme.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ExplicitUpwindScheme.cpp.s
.PHONY : ExplicitUpwindScheme.cpp.s

GeneralScheme.o: GeneralScheme.cpp.o

.PHONY : GeneralScheme.o

# target to build an object file
GeneralScheme.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/GeneralScheme.cpp.o
.PHONY : GeneralScheme.cpp.o

GeneralScheme.i: GeneralScheme.cpp.i

.PHONY : GeneralScheme.i

# target to preprocess a source file
GeneralScheme.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/GeneralScheme.cpp.i
.PHONY : GeneralScheme.cpp.i

GeneralScheme.s: GeneralScheme.cpp.s

.PHONY : GeneralScheme.s

# target to generate assembly for a file
GeneralScheme.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/GeneralScheme.cpp.s
.PHONY : GeneralScheme.cpp.s

ImplicitParallel.o: ImplicitParallel.cpp.o

.PHONY : ImplicitParallel.o

# target to build an object file
ImplicitParallel.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ImplicitParallel.cpp.o
.PHONY : ImplicitParallel.cpp.o

ImplicitParallel.i: ImplicitParallel.cpp.i

.PHONY : ImplicitParallel.i

# target to preprocess a source file
ImplicitParallel.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ImplicitParallel.cpp.i
.PHONY : ImplicitParallel.cpp.i

ImplicitParallel.s: ImplicitParallel.cpp.s

.PHONY : ImplicitParallel.s

# target to generate assembly for a file
ImplicitParallel.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ImplicitParallel.cpp.s
.PHONY : ImplicitParallel.cpp.s

ImplicitUpwindScheme.o: ImplicitUpwindScheme.cpp.o

.PHONY : ImplicitUpwindScheme.o

# target to build an object file
ImplicitUpwindScheme.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ImplicitUpwindScheme.cpp.o
.PHONY : ImplicitUpwindScheme.cpp.o

ImplicitUpwindScheme.i: ImplicitUpwindScheme.cpp.i

.PHONY : ImplicitUpwindScheme.i

# target to preprocess a source file
ImplicitUpwindScheme.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ImplicitUpwindScheme.cpp.i
.PHONY : ImplicitUpwindScheme.cpp.i

ImplicitUpwindScheme.s: ImplicitUpwindScheme.cpp.s

.PHONY : ImplicitUpwindScheme.s

# target to generate assembly for a file
ImplicitUpwindScheme.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/ImplicitUpwindScheme.cpp.s
.PHONY : ImplicitUpwindScheme.cpp.s

MathFunctions.o: MathFunctions.cpp.o

.PHONY : MathFunctions.o

# target to build an object file
MathFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/MathFunctions.cpp.o
.PHONY : MathFunctions.cpp.o

MathFunctions.i: MathFunctions.cpp.i

.PHONY : MathFunctions.i

# target to preprocess a source file
MathFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/MathFunctions.cpp.i
.PHONY : MathFunctions.cpp.i

MathFunctions.s: MathFunctions.cpp.s

.PHONY : MathFunctions.s

# target to generate assembly for a file
MathFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/MathFunctions.cpp.s
.PHONY : MathFunctions.cpp.s

Matrix.o: Matrix.cpp.o

.PHONY : Matrix.o

# target to build an object file
Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/Matrix.cpp.o
.PHONY : Matrix.cpp.o

Matrix.i: Matrix.cpp.i

.PHONY : Matrix.i

# target to preprocess a source file
Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/Matrix.cpp.i
.PHONY : Matrix.cpp.i

Matrix.s: Matrix.cpp.s

.PHONY : Matrix.s

# target to generate assembly for a file
Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/Matrix.cpp.s
.PHONY : Matrix.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/High_Performance_Technical_Computing.dir/build.make CMakeFiles/High_Performance_Technical_Computing.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... High_Performance_Technical_Computing"
	@echo "... CrankParallel.o"
	@echo "... CrankParallel.i"
	@echo "... CrankParallel.s"
	@echo "... Display.o"
	@echo "... Display.i"
	@echo "... Display.s"
	@echo "... ExplicitUpwindParallel.o"
	@echo "... ExplicitUpwindParallel.i"
	@echo "... ExplicitUpwindParallel.s"
	@echo "... ExplicitUpwindScheme.o"
	@echo "... ExplicitUpwindScheme.i"
	@echo "... ExplicitUpwindScheme.s"
	@echo "... GeneralScheme.o"
	@echo "... GeneralScheme.i"
	@echo "... GeneralScheme.s"
	@echo "... ImplicitParallel.o"
	@echo "... ImplicitParallel.i"
	@echo "... ImplicitParallel.s"
	@echo "... ImplicitUpwindScheme.o"
	@echo "... ImplicitUpwindScheme.i"
	@echo "... ImplicitUpwindScheme.s"
	@echo "... MathFunctions.o"
	@echo "... MathFunctions.i"
	@echo "... MathFunctions.s"
	@echo "... Matrix.o"
	@echo "... Matrix.i"
	@echo "... Matrix.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

